apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://helm.cilium.io
    targetRevision: 1.5.0
    chart: tetragon
    helm:
      values: |
        tetragon:
          enabled: true
          
          exportFilename: /var/log/tetragon/tetragon.log
          exportFileMaxSizeMB: 100
          exportFileRotationInterval: 24h
          exportRateLimit: 5000
          
          enableK8sAPI: true
          enableProcessCred: true
          enableProcessNs: true
          
          grpc:
            enabled: true
            address: 0.0.0.0:54321
          
          prometheus:
            enabled: true
            address: 0.0.0.0:2112
            serviceMonitor:
              enabled: true
              namespace: tetragon
          
          resources:
            limits:
              memory: 2Gi
              cpu: 2000m
            requests:
              memory: 512Mi
              cpu: 500m
              
        tetragonOperator:
          enabled: true
          
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: tetragon
          
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 128Mi
              cpu: 100m
  
  destination:
    server: https://kubernetes.default.svc
    namespace: tetragon
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m