apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      tolerations:
        - key: "workload"
          operator: "Equal"
          value: "demo"
          effect: "NoSchedule"
      nodeSelector:
        node-type: workload
      containers:
        - name: app
          image: ubuntu:22.04
          command: ["/bin/sleep", "infinity"]
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - NET_ADMIN
          volumeMounts:
            - name: host-filesystem
              mountPath: /host
              readOnly: true
      volumes:
        - name: host-filesystem
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app
  namespace: demo
spec:
  selector:
    app: vulnerable-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080