apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "sensitive-files"
  namespace: tetragon
spec:
  kprobes:
    # Monitor file access using fd_install
    - call: "fd_install"
      syscall: false
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "file"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Equal"
              values:
                - "/etc/shadow"
                - "/etc/passwd"
                - "/etc/gshadow"