apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "network-monitoring"
  namespace: tetragon
spec:
  kprobes:
    # Monitor UDP (already working)
    - call: "udp_sendmsg"
      syscall: false
      args:
        - index: 0
          type: "sock"
      selectors:
        - matchArgs:
            - index: 0
              operator: "DPort"
              values:
                - "53"    # DNS
                - "3333"  # Mining